# https://pnpm.io/settings

allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': true
  core-js: true
  electron-winstaller: true
  esbuild: true
  lightningcss: true
  protobufjs: false
  rolldown: true
  unrs-resolver: true
